// <auto-generated />
using System;
using Alza.Delivery.InfrastructureLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alza.Delivery.DataMigrations.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alza.Delivery.DomainLayer.Models.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("VanTripId")
                        .HasColumnType("text");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("VanTripId")
                        .HasDatabaseName("ix_packages_unassigned")
                        .HasFilter("\"VanTripId\" IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("VanTripId"), new[] { "Id", "Weight", "Volume", "Revenue" });

                    b.ToTable("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
