<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Alza.Delivery.InfrastructureLayer\Alza.Delivery.InfrastructureLayer.csproj" />
      <ProjectReference Include="..\Alza.Delivery.DomainLayer\Alza.Delivery.DomainLayer.csproj" />
      <ProjectReference Include="..\Alza.Delivery.InterfaceLayer\Alza.Delivery.InterfaceLayer.csproj" />
    </ItemGroup>

</Project>
