@Alza_HostAddress = http://localhost:5051

### 
POST {{Alza_HostAddress}}/api/orders
Content-Type: application/json

{
  "packages": [
    { "weightKg": 2.5, "volumeM3": 0.03, "revenueCzk": 450 },
    { "weightKg": 12, "volumeM3": 0.15, "revenueCzk": 1200 }
  ]
}

###
