@Alza_HostAddress = http://localhost:5051

### 
POST {{Alza_HostAddress}}/api/orders
Content-Type: application/json

{
  "packages": [
    { "weight": 2.5, "volume": 0.03, "revenue": 450 },
    { "weight": 12, "volume": 0.15, "revenue": 1200 }
  ]
}

###
